# -*- coding: utf-8 -*-
"""q06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jP7cQ1LyHlmLZpMnaaUUQU3N7v_YnNy9
"""

import numpy as np
import matplotlib.pyplot as plt
x = x = np.linspace(-5, 5, 500)
y = x**3 - 6 * x**2 + 9 * x - 3

xx = x + 2
yy = xx**3 - 6 * xx**2 + 9 * xx - 3 + 2

plt.figure(figsize=(10, 10))
plt.plot(x, y, color="red")
plt.plot(x, yy, color="blue")

plt.show()